version: '3.5'
services:
  webclient:
    image: nginx:latest
    container_name: webclient
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/webClient/out:/usr/share/nginx/html:ro
    ports:
    - 80:80
  certificategenerator:
    image: certgen
    container_name: certificategenerator
    restart: unless-stopped
    volumes:
     - /etc/localtime:/etc/localtime:ro
    environment:
     - PORT=9092
     - DOCKER=false
     - THREADS=true
     - MAX_BATCH_COMPILERS=2
     - MAX_COMPILERS=4
     - DEBUG=true
     - KEEP-FILES=true
  websockify:
    image: efrecon/websockify
    container_name: websockify
    restart: unless-stopped
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 9090:9090
    command: 9090 certificategenerator:9092
